dist: xenial

# blocklist
branches:
  except:
  - gh-pages

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - docker

env:
  global:
    - TMPDIR=/tmp

install:
  - curl -L https://git.io/get_helm.sh | bash -s -- -v v2.16.1
  - helm init --client-only
  - curl -sSL -o /tmp/ct.tgz https://github.com/helm/chart-testing/releases/download/v3.0.0-beta.1/chart-testing_3.0.0-beta.1_linux_amd64.tar.gz
  - tar xzf /tmp/ct.tgz -C /tmp && sudo cp /tmp/ct /usr/local/bin/ct && command -v ct

script:
  - make

deploy:
  - provider: pages
    token: ${GITHUB_TOKEN}
    target_branch: gh-pages
    local_dir: repo
    skip_cleanup: true
    keep_history: true
