kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "traefik.fullname" . }}
  annotations:
  {{- range $key, $value := .Values.serviceAccountAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
